--- 
- hosts: mygroup 
  become: yes
  tasks: 
      - name: m going to install apache
        apt: 
          name: "{{mywebserveronubuntu}}"
          state: present 
        when: ansible_os_family=="Debian"


      - name: m going to install apache on redhad
        yum: 
          name: "{{mywebserveronredhat}}"
          state: present 
        when: ansible_os_family=="RedHat"